name: cards
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/back_blue.png
   - assets/back_red.png
   - assets/clubs_2.png
   - assets/clubs_3.png
   - assets/clubs_4.png
   - assets/clubs_5.png
   - assets/clubs_6.png
   - assets/clubs_7.png
   - assets/clubs_8.png
   - assets/clubs_9.png
   - assets/clubs_10.png
   - assets/clubs_ace.png
   - assets/clubs_jack.png
   - assets/clubs_joker.png
   - assets/clubs_king.png
   - assets/clubs_queen.png
   - assets/diamond_2.png
   - assets/diamond_3.png
   - assets/diamond_4.png
   - assets/diamond_5.png
   - assets/diamond_6.png
   - assets/diamond_7.png
   - assets/diamond_8.png
   - assets/diamond_9.png
   - assets/diamond_10.png
   - assets/diamond_ace.png
   - assets/diamond_jack.png
   - assets/diamond_joker.png
   - assets/diamond_king.png
   - assets/diamond_queen.png
   - assets/heart_2.png
   - assets/heart_3.png
   - assets/heart_4.png
   - assets/heart_5.png
   - assets/heart_6.png
   - assets/heart_7.png
   - assets/heart_8.png
   - assets/heart_9.png
   - assets/heart_10.png
   - assets/heart_ace.png
   - assets/heart_jack.png
   - assets/heart_joker.png
   - assets/heart_king.png
   - assets/heart_queen.png
   - assets/spades_2.png
   - assets/spades_3.png
   - assets/spades_4.png
   - assets/spades_5.png
   - assets/spades_6.png
   - assets/spades_7.png
   - assets/spades_8.png
   - assets/spades_9.png
   - assets/spades_10.png
   - assets/spades_ace.png
   - assets/spades_jack.png
   - assets/spades_joker.png
   - assets/spades_king.png
   - assets/spades_queen.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
